theme: jekyll-theme-minimal
#remote_theme: kralizek/minimal-mistakes
title: Konstantin Matetski
logo: me_new.png
#
# --- Logo --- #
#
# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "me_new.png"
#
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
# round-avatar: true
#
# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: ./me_new.png
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kralizek"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/renatogolia/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Kralizek"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/82540"
#
# --- Navigation bar --- #
#
navigation:
  - name: Contact
    link: ./index.html
  - name: Research
    link: ./another-page.html
